import type { LeadWebhookPayload } from "./api";

/**
 * Fixture data inlined from fixtures/*.json in the repo root.
 * Used by the LeadTester component — no filesystem reads at runtime.
 */

export const FIXTURES: Record<string, LeadWebhookPayload> = {
  lead_bridge_fix_flip: {
    lead_id: "lead_001",
    submitted_at: "2026-03-07T09:15:00Z",
    first_name: "Marcus",
    last_name: "Bellamy",
    email: "marcus.bellamy@example-investors.com",
    phone: "404-555-0182",
    property_address: "2847 Glenwood Ave SE",
    property_city: "Atlanta",
    property_state: "GA",
    property_type: "Single Family",
    loan_amount_requested: 285000,
    purchase_price: 195000,
    estimated_arv: 385000,
    notes: "Looking to acquire and rehab this property. Already have contractors lined up. Need to close fast — seller wants 21 days. Have done 6 flips in the last 3 years in Atlanta metro.",
    source: "Google Ads",
    utm_campaign: "bridge-loan-atl-q1",
  },
  lead_rental_portfolio: {
    lead_id: "lead_002",
    submitted_at: "2026-03-06T14:22:00Z",
    first_name: "Diana",
    last_name: "Okafor",
    email: "diana.okafor@portfolio-holdings.com",
    phone: "216-555-0347",
    property_address: "1400–1422 West 58th St",
    property_city: "Cleveland",
    property_state: "OH",
    property_type: "Multi-Family (11 units)",
    loan_amount_requested: 1450000,
    purchase_price: null,
    estimated_arv: null,
    notes: "Looking to refinance my 11-unit portfolio in Cleveland. Current DSCR is 1.35 across all units, fully occupied with long-term tenants. Monthly gross rental income is $14,200. Want to pull cash out for a second portfolio acquisition in Akron. Have been a landlord for 9 years with 23 doors total.",
    source: "Referral",
    utm_campaign: null,
  },
  lead_first_time_vague: {
    lead_id: "lead_003",
    submitted_at: "2026-03-07T11:05:00Z",
    first_name: "Tyler",
    last_name: "Nguyen",
    email: "tyler.nguyen@gmail.com",
    phone: "480-555-0291",
    property_address: null,
    property_city: "Phoenix",
    property_state: "AZ",
    property_type: null,
    loan_amount_requested: null,
    purchase_price: null,
    estimated_arv: null,
    notes: "I've been watching a lot of videos about real estate investing and I think I'm ready to get started. Not sure if I should flip or rent. How does the loan process work? Do I need a lot of money down? I'm looking at properties in the Phoenix area but haven't found anything specific yet.",
    source: "Facebook Ads",
    utm_campaign: "first-time-investor-az",
  },
  lead_commercial_bridge: {
    lead_id: "lead_004",
    submitted_at: "2026-03-05T16:40:00Z",
    first_name: "Rachel",
    last_name: "Dominguez",
    email: "rachel@suncoast-capital-group.com",
    phone: "813-555-0164",
    property_address: "9200 N Florida Ave",
    property_city: "Tampa",
    property_state: "FL",
    property_type: "Multi-Family (24 units)",
    loan_amount_requested: 2800000,
    purchase_price: 3200000,
    estimated_arv: 4500000,
    notes: "Value-add acquisition of a 24-unit garden-style complex. Current occupancy is 71% with below-market rents. Plan is a 12-month rehab to stabilize at 95%+ occupancy, then refi into permanent DSCR. Need bridge financing to close and fund renovations. We've completed three similar projects in the Tampa Bay area over the past five years.",
    source: "Direct",
    utm_campaign: null,
  },
  lead_sparse: {
    lead_id: "lead_005",
    first_name: "Jordan",
    last_name: "Smith",
    email: "jsmith99@yahoo.com",
  },
  lead_contradictory: {
    lead_id: "lead_006",
    submitted_at: "2026-03-07T08:30:00Z",
    first_name: "Kevin",
    last_name: "Patel",
    email: "kevin.patel@outlook.com",
    phone: "512-555-0438",
    property_address: "3310 E Riverside Dr",
    property_city: "Austin",
    property_state: "TX",
    property_type: "Single Family",
    loan_amount_requested: 340000,
    purchase_price: 275000,
    estimated_arv: 410000,
    notes: "Found a great deal — planning to rehab and flip within 6 months, but also considering keeping it as a long-term rental if the cash flow makes sense. ARV looks strong for a flip but the neighborhood rental comps are solid too. Would love to understand both exit strategies. Might also BRRRR it. First time doing this on my own but I've partnered on two deals before.",
    source: "Google Ads",
    utm_campaign: "bridge-loan-tx-q1",
  },
  lead_experienced_rental_sfr: {
    lead_id: "lead_007",
    submitted_at: "2026-03-06T09:50:00Z",
    first_name: "Aisha",
    last_name: "Montgomery",
    email: "aisha@montgomery-properties.com",
    phone: "602-555-0215",
    property_address: "4412 N 19th Ave",
    property_city: "Phoenix",
    property_state: "AZ",
    property_type: "Single Family",
    loan_amount_requested: 225000,
    purchase_price: 310000,
    estimated_arv: null,
    notes: "Adding another SFR to my rental portfolio. Tenant already in place paying $1,850/mo on a 12-month lease. DSCR should be well above 1.25. This will be my 8th rental property — all in the Phoenix metro. Looking for a 30-year fixed DSCR loan, no prepayment penalty preferred.",
    source: "Email Campaign",
    utm_campaign: "dscr-rental-az",
  },
};

export const FIXTURE_NAMES = Object.keys(FIXTURES);
