import type { LeadWebhookPayload } from "./api";

/**
 * Fixture data — 5 variations per theme for diverse sample generation.
 * Used by the LeadTester component — no filesystem reads at runtime.
 */

export const FIXTURES: Record<string, LeadWebhookPayload[]> = {
  lead_bridge_fix_flip: [
    {
      lead_id: "lead_001",
      submitted_at: "2026-03-07T09:15:00Z",
      first_name: "Marcus",
      last_name: "Bellamy",
      email: "marcus.bellamy@example-investors.com",
      phone: "404-555-0182",
      property_address: "2847 Glenwood Ave SE",
      property_city: "Atlanta",
      property_state: "GA",
      property_type: "Single Family",
      loan_amount_requested: 285000,
      purchase_price: 195000,
      estimated_arv: 385000,
      notes:
        "Looking to acquire and rehab this property. Already have contractors lined up. Need to close fast — seller wants 21 days. Have done 6 flips in the last 3 years in Atlanta metro.",
      source: "Google Ads",
      utm_campaign: "bridge-loan-atl-q1",
    },
    {
      lead_id: "lead_001b",
      submitted_at: "2026-03-07T10:30:00Z",
      first_name: "Janelle",
      last_name: "Cross",
      email: "janelle@crossflips.com",
      phone: "901-555-0244",
      property_address: "1885 Lamar Ave",
      property_city: "Memphis",
      property_state: "TN",
      property_type: "Single Family",
      loan_amount_requested: 165000,
      purchase_price: 120000,
      estimated_arv: 230000,
      notes:
        "Estate sale — needs full gut rehab. ARV based on three recent comps within half a mile. Planning 4-month renovation timeline. This is my 10th flip. Need bridge financing to close in 14 days.",
      source: "Zillow",
      utm_campaign: "bridge-loan-tn-q1",
    },
    {
      lead_id: "lead_001c",
      submitted_at: "2026-03-06T15:45:00Z",
      first_name: "Derek",
      last_name: "Hawkins",
      email: "derek.hawkins@rapidclose.net",
      phone: "317-555-0198",
      property_address: "4520 E Washington St",
      property_city: "Indianapolis",
      property_state: "IN",
      property_type: "Single Family",
      loan_amount_requested: 210000,
      purchase_price: 155000,
      estimated_arv: 310000,
      notes:
        "Off-market deal from a wholesaler. Property needs cosmetic rehab — new kitchen, bathrooms, flooring. Expecting 90-day turnaround. Have done 3 flips this year already. Need to close within two weeks.",
      source: "Direct",
      utm_campaign: null,
    },
    {
      lead_id: "lead_001d",
      submitted_at: "2026-03-08T08:20:00Z",
      first_name: "Priya",
      last_name: "Sharma",
      email: "priya@sharmarei.com",
      phone: "704-555-0331",
      property_address: "609 Beatties Ford Rd",
      property_city: "Charlotte",
      property_state: "NC",
      property_type: "Single Family",
      loan_amount_requested: 340000,
      purchase_price: 245000,
      estimated_arv: 465000,
      notes:
        "Foreclosure acquisition — bank is motivated. Major value-add opportunity: add a second story and convert to duplex. My architect already submitted plans. Need transitional financing. Have completed 8 rehab projects since 2022.",
      source: "Google Ads",
      utm_campaign: "bridge-loan-nc-q1",
    },
    {
      lead_id: "lead_001e",
      submitted_at: "2026-03-07T13:10:00Z",
      first_name: "Carlos",
      last_name: "Medina",
      email: "carlos.medina@flipfast.io",
      phone: "210-555-0477",
      property_address: "7733 Culebra Rd",
      property_city: "San Antonio",
      property_state: "TX",
      property_type: "Single Family",
      loan_amount_requested: 195000,
      purchase_price: 140000,
      estimated_arv: 275000,
      notes:
        "Fix and flip in an up-and-coming neighborhood. Rehab budget is $55K — contractor starts next week. Need to close fast before another buyer steps in. This is my 15th flip in the San Antonio market.",
      source: "Referral",
      utm_campaign: null,
    },
  ],

  lead_rental_portfolio: [
    {
      lead_id: "lead_002",
      submitted_at: "2026-03-06T14:22:00Z",
      first_name: "Diana",
      last_name: "Okafor",
      email: "diana.okafor@portfolio-holdings.com",
      phone: "216-555-0347",
      property_address: "1400–1422 West 58th St",
      property_city: "Cleveland",
      property_state: "OH",
      property_type: "Multi-Family (11 units)",
      loan_amount_requested: 1450000,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "Looking to refinance my 11-unit portfolio in Cleveland. Current DSCR is 1.35 across all units, fully occupied with long-term tenants. Monthly gross rental income is $14,200. Want to pull cash out for a second portfolio acquisition in Akron. Have been a landlord for 9 years with 23 doors total.",
      source: "Referral",
      utm_campaign: null,
    },
    {
      lead_id: "lead_002b",
      submitted_at: "2026-03-05T11:15:00Z",
      first_name: "Robert",
      last_name: "Tran",
      email: "robert.tran@midwestrentals.com",
      phone: "614-555-0188",
      property_address: "880 Bryden Rd",
      property_city: "Columbus",
      property_state: "OH",
      property_type: "Multi-Family (4 units)",
      loan_amount_requested: 420000,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "Cash-out refinance on my fourplex. DSCR is 1.42 — all units occupied with tenants on 12-month leases. Gross monthly rent is $5,200. Want to use the cash to acquire two more duplexes. Have 12 doors across Columbus. Looking for a 30-year fixed rental loan.",
      source: "Email Campaign",
      utm_campaign: "dscr-refi-oh",
    },
    {
      lead_id: "lead_002c",
      submitted_at: "2026-03-07T09:00:00Z",
      first_name: "Sandra",
      last_name: "Whitfield",
      email: "sandra@whitfieldpm.com",
      phone: "414-555-0265",
      property_address: "2310 N Farwell Ave",
      property_city: "Milwaukee",
      property_state: "WI",
      property_type: "Multi-Family (8 units)",
      loan_amount_requested: 880000,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "Portfolio refinance — own 8 units in a single building, fully occupied for 3 years. DSCR is 1.28. Monthly gross rental income $9,600. Looking to lock in a long-term fixed rate before rates move. Have been a landlord for 14 years with 31 doors.",
      source: "Direct",
      utm_campaign: null,
    },
    {
      lead_id: "lead_002d",
      submitted_at: "2026-03-06T16:40:00Z",
      first_name: "James",
      last_name: "Patterson",
      email: "james@pattersonholdings.net",
      phone: "502-555-0412",
      property_address: "1155 Bardstown Rd",
      property_city: "Louisville",
      property_state: "KY",
      property_type: "Multi-Family (6 units)",
      loan_amount_requested: 650000,
      purchase_price: 720000,
      estimated_arv: null,
      notes:
        "Acquiring a 6-unit building — tenants already in place, 83% occupancy, DSCR 1.18 at current rents. Expecting to push rents 10% after cosmetic upgrades. Want DSCR financing with no income docs. Have 18 rental units in Louisville already.",
      source: "Google Ads",
      utm_campaign: "rental-loan-ky-q1",
    },
    {
      lead_id: "lead_002e",
      submitted_at: "2026-03-08T07:30:00Z",
      first_name: "Lisa",
      last_name: "Chen",
      email: "lisa.chen@pacificrentals.com",
      phone: "503-555-0199",
      property_address: "4820 SE Division St",
      property_city: "Portland",
      property_state: "OR",
      property_type: "Multi-Family (16 units)",
      loan_amount_requested: 2100000,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "Refinancing a 16-unit apartment building. Fully stabilized — 94% occupancy, DSCR 1.51, gross monthly rental income $28,400. Want to pull equity for a new 20-unit acquisition in Salem. Have been managing rental properties for 11 years with 42 doors total.",
      source: "Referral",
      utm_campaign: null,
    },
  ],

  lead_first_time_vague: [
    {
      lead_id: "lead_003",
      submitted_at: "2026-03-07T11:05:00Z",
      first_name: "Tyler",
      last_name: "Nguyen",
      email: "tyler.nguyen@gmail.com",
      phone: "480-555-0291",
      property_address: null,
      property_city: "Phoenix",
      property_state: "AZ",
      property_type: null,
      loan_amount_requested: null,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "I've been watching a lot of videos about real estate investing and I think I'm ready to get started. Not sure if I should flip or rent. How does the loan process work? Do I need a lot of money down? I'm looking at properties in the Phoenix area but haven't found anything specific yet.",
      source: "Facebook Ads",
      utm_campaign: "first-time-investor-az",
    },
    {
      lead_id: "lead_003b",
      submitted_at: "2026-03-06T18:30:00Z",
      first_name: "Ashley",
      last_name: "Rivera",
      email: "ashley.rivera@hotmail.com",
      phone: "305-555-0177",
      property_address: null,
      property_city: "Miami",
      property_state: "FL",
      property_type: null,
      loan_amount_requested: null,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "First time looking into real estate investing. A friend told me about house flipping. I have about $30K saved up. What kind of properties can I afford? How does financing work for beginners? I'm interested in the Miami area.",
      source: "Instagram Ads",
      utm_campaign: "first-time-investor-fl",
    },
    {
      lead_id: "lead_003c",
      submitted_at: "2026-03-07T14:20:00Z",
      first_name: "Brandon",
      last_name: "Kim",
      email: "brandon.j.kim@gmail.com",
      phone: "702-555-0355",
      property_address: null,
      property_city: "Las Vegas",
      property_state: "NV",
      property_type: null,
      loan_amount_requested: null,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "Just got pre-approved for a conventional mortgage but wondering if investment property loans work differently. I want to get started with a rental property. How does the process work? What's the minimum down payment? I'm exploring neighborhoods in Vegas.",
      source: "Facebook Ads",
      utm_campaign: "first-time-investor-nv",
    },
    {
      lead_id: "lead_003d",
      submitted_at: "2026-03-08T10:15:00Z",
      first_name: "Megan",
      last_name: "Larsen",
      email: "megan.larsen@yahoo.com",
      phone: "720-555-0488",
      property_address: null,
      property_city: "Denver",
      property_state: "CO",
      property_type: null,
      loan_amount_requested: null,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "I'm a first time investor and I've been reading about BRRRR strategy. Seems like a great way to build wealth. But I have no experience yet and I'm not sure where to start. Can you walk me through how the loan works? I'm looking at Denver suburbs.",
      source: "TikTok Ads",
      utm_campaign: "first-time-investor-co",
    },
    {
      lead_id: "lead_003e",
      submitted_at: "2026-03-07T16:50:00Z",
      first_name: "Noah",
      last_name: "Washington",
      email: "noah.wash@outlook.com",
      phone: "615-555-0232",
      property_address: null,
      property_city: "Nashville",
      property_state: "TN",
      property_type: null,
      loan_amount_requested: null,
      purchase_price: null,
      estimated_arv: null,
      notes:
        "Thinking about getting into real estate. I currently work in tech and want passive income. Don't know much about the process yet. How do I get started? What kind of returns should I expect? Nashville market seems hot.",
      source: "Google Ads",
      utm_campaign: "first-time-investor-tn",
    },
  ],

  lead_commercial_bridge: [
    {
      lead_id: "lead_004",
      submitted_at: "2026-03-05T16:40:00Z",
      first_name: "Rachel",
      last_name: "Dominguez",
      email: "rachel@suncoast-capital-group.com",
      phone: "813-555-0164",
      property_address: "9200 N Florida Ave",
      property_city: "Tampa",
      property_state: "FL",
      property_type: "Multi-Family (24 units)",
      loan_amount_requested: 2800000,
      purchase_price: 3200000,
      estimated_arv: 4500000,
      notes:
        "Value-add acquisition of a 24-unit garden-style complex. Current occupancy is 71% with below-market rents. Plan is a 12-month rehab to stabilize at 95%+ occupancy, then refi into permanent DSCR. Need bridge financing to close and fund renovations. We've completed three similar projects in the Tampa Bay area over the past five years.",
      source: "Direct",
      utm_campaign: null,
    },
    {
      lead_id: "lead_004b",
      submitted_at: "2026-03-06T09:20:00Z",
      first_name: "Anthony",
      last_name: "Brooks",
      email: "anthony@brooksventures.com",
      phone: "972-555-0311",
      property_address: "5500 Maple Ave",
      property_city: "Dallas",
      property_state: "TX",
      property_type: "Multi-Family (18 units)",
      loan_amount_requested: 2100000,
      purchase_price: 2400000,
      estimated_arv: 3600000,
      notes:
        "Acquiring an 18-unit complex — current occupancy 65%, significant deferred maintenance. Plan to renovate units, upgrade common areas, and stabilize at market rents within 10 months. Need bridge loan to fund acquisition and $450K in renovations. Have done 4 similar value-add projects in DFW.",
      source: "Referral",
      utm_campaign: null,
    },
    {
      lead_id: "lead_004c",
      submitted_at: "2026-03-07T11:45:00Z",
      first_name: "Natalie",
      last_name: "Foster",
      email: "natalie@elevatepropertygroup.com",
      phone: "404-555-0289",
      property_address: "3200 Peachtree Rd NE",
      property_city: "Atlanta",
      property_state: "GA",
      property_type: "Multi-Family (32 units)",
      loan_amount_requested: 3800000,
      purchase_price: 4200000,
      estimated_arv: 6100000,
      notes:
        "32-unit acquisition in Buckhead area. Currently underperforming — 68% occupied with dated units. Our plan is a full interior renovation, new amenities, and professional management. 14-month stabilization timeline. Need transitional financing. We've stabilized over 200 units across three states.",
      source: "Direct",
      utm_campaign: null,
    },
    {
      lead_id: "lead_004d",
      submitted_at: "2026-03-05T14:10:00Z",
      first_name: "Victor",
      last_name: "Gupta",
      email: "victor@pinnacle-acquisitions.com",
      phone: "602-555-0166",
      property_address: "8401 N 27th Ave",
      property_city: "Phoenix",
      property_state: "AZ",
      property_type: "Multi-Family (12 units)",
      loan_amount_requested: 1550000,
      purchase_price: 1800000,
      estimated_arv: 2600000,
      notes:
        "Value-add 12-unit in north Phoenix. Occupancy at 75% with below-market rents. Rehab plan includes new HVAC, roofing, and unit interiors. Budget is $320K in renovations over 8 months. Need bridge financing for acquisition and rehab draws. Completed two similar projects this year.",
      source: "Google Ads",
      utm_campaign: "bridge-commercial-az",
    },
    {
      lead_id: "lead_004e",
      submitted_at: "2026-03-08T08:55:00Z",
      first_name: "Christina",
      last_name: "Reeves",
      email: "christina@summitcapitalre.com",
      phone: "615-555-0447",
      property_address: "2120 Dickerson Pike",
      property_city: "Nashville",
      property_state: "TN",
      property_type: "Multi-Family (20 units)",
      loan_amount_requested: 2400000,
      purchase_price: 2750000,
      estimated_arv: 4000000,
      notes:
        "20-unit garden-style acquisition in East Nashville. 60% occupied, significant value-add potential. Planning $600K renovation over 12 months to stabilize at 95%+ occupancy. Exit strategy is permanent DSCR financing. Our firm has completed five similar multifamily renovations in Tennessee.",
      source: "Direct",
      utm_campaign: null,
    },
  ],

  lead_sparse: [
    {
      lead_id: "lead_005",
      first_name: "Jordan",
      last_name: "Smith",
      email: "jsmith99@yahoo.com",
    },
    {
      lead_id: "lead_005b",
      first_name: "Taylor",
      last_name: "Brown",
      email: "taylor.brown@gmail.com",
    },
    {
      lead_id: "lead_005c",
      first_name: "Casey",
      last_name: "Williams",
      email: "casey.w@outlook.com",
      phone: "555-555-0100",
    },
    {
      lead_id: "lead_005d",
      first_name: "Morgan",
      last_name: "Davis",
      email: "morgandavis@gmail.com",
      property_city: "Chicago",
      property_state: "IL",
    },
    {
      lead_id: "lead_005e",
      first_name: "Riley",
      last_name: "Johnson",
      email: "riley.j@yahoo.com",
      notes: "Interested in investing",
    },
  ],

  lead_contradictory: [
    {
      lead_id: "lead_006",
      submitted_at: "2026-03-07T08:30:00Z",
      first_name: "Kevin",
      last_name: "Patel",
      email: "kevin.patel@outlook.com",
      phone: "512-555-0438",
      property_address: "3310 E Riverside Dr",
      property_city: "Austin",
      property_state: "TX",
      property_type: "Single Family",
      loan_amount_requested: 340000,
      purchase_price: 275000,
      estimated_arv: 410000,
      notes:
        "Found a great deal — planning to rehab and flip within 6 months, but also considering keeping it as a long-term rental if the cash flow makes sense. ARV looks strong for a flip but the neighborhood rental comps are solid too. Would love to understand both exit strategies. Might also BRRRR it. First time doing this on my own but I've partnered on two deals before.",
      source: "Google Ads",
      utm_campaign: "bridge-loan-tx-q1",
    },
    {
      lead_id: "lead_006b",
      submitted_at: "2026-03-06T12:15:00Z",
      first_name: "Samantha",
      last_name: "Lee",
      email: "samantha.lee@protonmail.com",
      phone: "503-555-0321",
      property_address: "1845 SE Hawthorne Blvd",
      property_city: "Portland",
      property_state: "OR",
      property_type: "Duplex",
      loan_amount_requested: 450000,
      purchase_price: 380000,
      estimated_arv: 520000,
      notes:
        "Looking at a duplex — could flip the whole thing or rent one unit and live in the other. The upstairs needs full renovation but the downstairs is turnkey. Not sure if I should treat this as a rental or a fix and flip. I've done one renovation before but it was my primary residence, not an investment. What loan makes sense here?",
      source: "Facebook Ads",
      utm_campaign: "investor-or-q1",
    },
    {
      lead_id: "lead_006c",
      submitted_at: "2026-03-07T15:40:00Z",
      first_name: "Andre",
      last_name: "Jackson",
      email: "andre.jackson@gmail.com",
      phone: "404-555-0512",
      property_address: "587 Memorial Dr SE",
      property_city: "Atlanta",
      property_state: "GA",
      property_type: "Single Family",
      loan_amount_requested: 280000,
      purchase_price: 210000,
      estimated_arv: 360000,
      notes:
        "This property has great flip potential but it's also in a strong rental market. I want to rehab it and then decide — if the market is hot I'll sell, otherwise I'll hold as a rental. My timeline is flexible. I've completed 2 flips and own 1 rental already. Need financing that gives me flexibility.",
      source: "Google Ads",
      utm_campaign: "bridge-loan-ga-q1",
    },
    {
      lead_id: "lead_006d",
      submitted_at: "2026-03-08T09:10:00Z",
      first_name: "Olivia",
      last_name: "Torres",
      email: "olivia.torres@investflex.com",
      phone: "214-555-0278",
      property_address: "4200 Gaston Ave",
      property_city: "Dallas",
      property_state: "TX",
      property_type: "Single Family",
      loan_amount_requested: 310000,
      purchase_price: 240000,
      estimated_arv: 395000,
      notes:
        "Interested in a BRRRR deal — buy, rehab, rent, refinance, repeat. But I might just flip it depending on how the renovation goes. I want a short-term loan initially and then maybe convert to a rental loan. First time doing BRRRR but I've been a landlord with 3 properties for two years. Also exploring partnerships if the numbers work.",
      source: "Referral",
      utm_campaign: null,
    },
    {
      lead_id: "lead_006e",
      submitted_at: "2026-03-06T17:25:00Z",
      first_name: "Jason",
      last_name: "Murphy",
      email: "jason.murphy@outlook.com",
      phone: "813-555-0394",
      property_address: "3100 W Gandy Blvd",
      property_city: "Tampa",
      property_state: "FL",
      property_type: "Townhouse",
      loan_amount_requested: 265000,
      purchase_price: 200000,
      estimated_arv: 340000,
      notes:
        "Townhouse near the waterfront — great location for both flipping and renting. I'm leaning toward a quick flip but my business partner wants to hold it as an Airbnb. We haven't decided yet. We've done one project together before. Need to close quickly because there's another offer. How fast can you fund?",
      source: "Google Ads",
      utm_campaign: "bridge-loan-fl-q1",
    },
  ],

  lead_experienced_rental_sfr: [
    {
      lead_id: "lead_007",
      submitted_at: "2026-03-06T09:50:00Z",
      first_name: "Aisha",
      last_name: "Montgomery",
      email: "aisha@montgomery-properties.com",
      phone: "602-555-0215",
      property_address: "4412 N 19th Ave",
      property_city: "Phoenix",
      property_state: "AZ",
      property_type: "Single Family",
      loan_amount_requested: 225000,
      purchase_price: 310000,
      estimated_arv: null,
      notes:
        "Adding another SFR to my rental portfolio. Tenant already in place paying $1,850/mo on a 12-month lease. DSCR should be well above 1.25. This will be my 8th rental property — all in the Phoenix metro. Looking for a 30-year fixed DSCR loan, no prepayment penalty preferred.",
      source: "Email Campaign",
      utm_campaign: "dscr-rental-az",
    },
    {
      lead_id: "lead_007b",
      submitted_at: "2026-03-07T08:15:00Z",
      first_name: "William",
      last_name: "Carter",
      email: "william@carterrentals.net",
      phone: "901-555-0188",
      property_address: "3255 Summer Ave",
      property_city: "Memphis",
      property_state: "TN",
      property_type: "Single Family",
      loan_amount_requested: 145000,
      purchase_price: 190000,
      estimated_arv: null,
      notes:
        "Purchasing a stabilized SFR rental — tenant in place paying $1,400/mo, lease runs through next February. DSCR is 1.38. This is my 12th rental property. Have been investing in Memphis for 7 years. Want a 30-year DSCR loan with interest-only option for the first 3 years.",
      source: "Email Campaign",
      utm_campaign: "dscr-rental-tn",
    },
    {
      lead_id: "lead_007c",
      submitted_at: "2026-03-06T13:30:00Z",
      first_name: "Grace",
      last_name: "Nakamura",
      email: "grace@nakamurainvestments.com",
      phone: "816-555-0277",
      property_address: "1520 E 63rd St",
      property_city: "Kansas City",
      property_state: "MO",
      property_type: "Single Family",
      loan_amount_requested: 120000,
      purchase_price: 165000,
      estimated_arv: null,
      notes:
        "Adding property #15 to my rental portfolio. Section 8 tenant already placed, paying $1,250/mo with housing authority guarantee. DSCR is 1.45. I've been a landlord for 10 years — all single-family in KC metro. Looking for a standard DSCR loan, 30-year fixed.",
      source: "Referral",
      utm_campaign: null,
    },
    {
      lead_id: "lead_007d",
      submitted_at: "2026-03-08T10:00:00Z",
      first_name: "Marcus",
      last_name: "Robinson",
      email: "marcus@robinsonpropertygroup.com",
      phone: "317-555-0344",
      property_address: "2840 N Illinois St",
      property_city: "Indianapolis",
      property_state: "IN",
      property_type: "Single Family",
      loan_amount_requested: 155000,
      purchase_price: 210000,
      estimated_arv: null,
      notes:
        "Expanding my SFR portfolio — this will be door #20. Current tenant paying $1,550/mo on a 2-year lease. DSCR is 1.32. Have been building my portfolio for 8 years across Indianapolis. Need a DSCR loan — no income verification. Prefer 30-year fixed with no prepayment penalty.",
      source: "Google Ads",
      utm_campaign: "dscr-rental-in",
    },
    {
      lead_id: "lead_007e",
      submitted_at: "2026-03-07T15:20:00Z",
      first_name: "Stephanie",
      last_name: "Flores",
      email: "stephanie@floresrei.com",
      phone: "210-555-0199",
      property_address: "6700 Bandera Rd",
      property_city: "San Antonio",
      property_state: "TX",
      property_type: "Single Family",
      loan_amount_requested: 180000,
      purchase_price: 245000,
      estimated_arv: null,
      notes:
        "Closing on my 6th rental — tenant in place at $1,700/mo with a 14-month lease. DSCR is 1.29. All my properties are in San Antonio. Have been investing for 5 years. Looking for a 30-year term DSCR loan. Want to refinance out of a hard money loan I used to acquire this one.",
      source: "Direct",
      utm_campaign: null,
    },
  ],
};

export const FIXTURE_NAMES = Object.keys(FIXTURES);
